### ISSUE TITLE
Build Failure: Could not determine java version from '9.0.4'.

### ISSUE THREAD

**Issue by ph1l** [staltz/mmmmm-mobile#46]
```
~/code/mmmmm-mobile$ react-native run-android
Scanning folders for symlinks in /home/ssb/code/mmmmm-mobile/node_modules (12ms)
Starting JS server...
Building and installing the app on the device (cd android && ./gradlew installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '9.0.4'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by staltz** [comment]
Hi! Could you share more details? When opening an issue, we have a template message, where you should provide reproducing steps, and more technical details like which node version, which npm, what operating system, etc. 

Also, since this command `react-native run-android` is standard workflow when using React Native, please follow installation instructions for that framework, see more here: https://facebook.github.io/react-native/docs/getting-started.html

**Comment by ph1l** [comment]
To reproduce: followed instructions in README for building

```
~$ node --version
v8.10.1-pre
~$ npm --version
5.7.1
~$ lsb_release --all
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux unstable (sid)
Release:        unstable
Codename:       sid
```

**Comment by staltz** [comment]
Did you also install Android SDKs like the React Native docs explain?

**Comment by ph1l** [comment]
Oh, I see you have two lists of different dependencies in your readme.. my bad.
