### ISSUE TITLE
0.0.8 app crashes

### ISSUE THREAD

**Issue by alanz** [staltz/mmmmm-mobile#8]
I reinstalled the app, and cleared its data via the settings/apps

It connected via my local wifi to my machine, I followed and followed back to make friends.

It then started the normal sync process. This runs for a while, and then the app just stops.

After a restart, it continues syncing, only to crash again a bit later. 

The storage being used is increasing, and it looks like the content is changing over time, so I am continuing to restart it to see if it every catches up, and then stabilises.

**Comment by alanz** [comment]
This is a OnePlus 5

**Comment by staltz** [comment]
Hi @alanz  :)
Thanks for letting me know.  It might be due to a certain message that has nested lists:

> - A
>   - A1
>   - A2
>   - A3
> - B

You can try if that's the case by wiping the data, then syncing the mobile app with a clean desktop scuttlebot that publishes just one message, with a nested list in markdown. If it crashes, that's the problem. I already fixed that problem today, it's in the master branch but unreleased.

For now, this issue lacks more details for a bug reproduction.
